// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/exams": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "查询管理员所属试卷",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在页面 默认值：1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分页大小 默认值：10",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.GetExamsResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.GetExamsResponse"
                        }
                    }
                }
            }
        },
        "/admin/exams/exam": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "创建试卷",
                "parameters": [
                    {
                        "description": "题目id列表",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ExamReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.ExamResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.ExamResponse"
                        }
                    }
                }
            }
        },
        "/admin/exams/exam/:id": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "编辑试卷",
                "parameters": [
                    {
                        "type": "string",
                        "description": "试卷id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "试卷id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ExamReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.ExamResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.ExamResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "删除试卷",
                "parameters": [
                    {
                        "type": "string",
                        "description": "试卷id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.ExamResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.ExamResponse"
                        }
                    }
                }
            }
        },
        "/admin/questions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "查询所有题目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在页面 默认值：1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分页大小 默认值：10",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.GetQuestionsResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.GetQuestionsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "添加新问题",
                "parameters": [
                    {
                        "description": "问题",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AddQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.AddQuestionResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.AddQuestionResponse"
                        }
                    }
                }
            }
        },
        "/admin/questions/:id": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "编辑问题",
                "parameters": [
                    {
                        "type": "string",
                        "description": "问题id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "问题",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.EditQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.AddQuestionResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.AddQuestionResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "删除问题",
                "parameters": [
                    {
                        "type": "string",
                        "description": "问题id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.DelQuestionResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.DelQuestionResponse"
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "manage users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在页面 默认值：1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分页大小 默认值：10",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"登陆成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/users/:id/exams": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "user exam history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "所在页面 默认值：1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分页大小 默认值：10",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "model.Response{data: response.GetExamHistoryResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.GetExamHistoryResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/:id/questions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "user question history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "所在页面 默认值：1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分页大小 默认值：10",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"登陆成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/base/captcha": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "生成验证码",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"验证码获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/base/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户名, 密码, 验证码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"登陆成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/casbin/UpdateCasbin": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Casbin"
                ],
                "summary": "更新角色api权限",
                "parameters": [
                    {
                        "description": "权限id, 权限模型列表",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CasbinInReceive"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"更新成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/casbin/getPolicyPathByAuthorityId": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Casbin"
                ],
                "summary": "获取权限列表",
                "parameters": [
                    {
                        "description": "权限id, 权限模型列表",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CasbinInReceive"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/chapters": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chapters"
                ],
                "summary": "获取所有章节",
                "responses": {
                    "200": {
                        "description": "response.Response{data: GetChaptersResponse}",
                        "schema": {
                            "$ref": "#/definitions/v1.GetChaptersResponse"
                        }
                    }
                }
            }
        },
        "/email/emailTest": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "发送测试邮件",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"发送成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/exams": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exam"
                ],
                "summary": "查询所有试卷",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在页面 默认值：1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分页大小 默认值：10",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "所属用户 id",
                        "name": "userId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.GetExamsResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.GetExamsResponse"
                        }
                    }
                }
            }
        },
        "/exams/answer/:id": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exam"
                ],
                "summary": "查询试卷答题情况",
                "parameters": [
                    {
                        "type": "string",
                        "description": "答卷id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.ExamResultResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.ExamResultResponse"
                        }
                    }
                }
            }
        },
        "/exams/exam/:id": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exam"
                ],
                "summary": "查询某个试卷",
                "parameters": [
                    {
                        "type": "string",
                        "description": "试卷id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.ExamResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.ExamResponse"
                        }
                    }
                }
            }
        },
        "/exams/random": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exam"
                ],
                "summary": "获取随机试卷",
                "responses": {
                    "200": {
                        "description": "response.Response{data: request.Exam}",
                        "schema": {
                            "$ref": "#/definitions/request.Exam"
                        }
                    }
                }
            }
        },
        "/exams/submit": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exam"
                ],
                "summary": "提交试卷",
                "parameters": [
                    {
                        "description": "试卷答案",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ExamAnswer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SubmitExamResponse"
                        }
                    }
                }
            }
        },
        "/fileUploadAndDownload/breakpointContinue": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExaFileUploadAndDownload"
                ],
                "summary": "断点续传到服务器",
                "parameters": [
                    {
                        "type": "file",
                        "description": "an example for breakpoint resume, 断点续传示例",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"切片创建成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fileUploadAndDownload/deleteFile": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExaFileUploadAndDownload"
                ],
                "summary": "删除文件",
                "parameters": [
                    {
                        "description": "传入文件里面id即可",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ExaFileUploadAndDownload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fileUploadAndDownload/findFile": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExaFileUploadAndDownload"
                ],
                "summary": "创建文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "上传文件完成",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"file uploaded, 文件创建成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fileUploadAndDownload/getFileList": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExaFileUploadAndDownload"
                ],
                "summary": "分页文件列表",
                "parameters": [
                    {
                        "description": "页码, 每页大小",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PageInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fileUploadAndDownload/removeChunk": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExaFileUploadAndDownload"
                ],
                "summary": "删除切片",
                "parameters": [
                    {
                        "type": "file",
                        "description": "删除缓存切片",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"缓存切片删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fileUploadAndDownload/upload": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ExaFileUploadAndDownload"
                ],
                "summary": "上传文件示例",
                "parameters": [
                    {
                        "type": "file",
                        "description": "上传文件示例",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"上传成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/init/initdb": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "InitDB"
                ],
                "summary": "初始化用户数据库",
                "parameters": [
                    {
                        "description": "初始化数据库参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.InitDB"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"data\":{},\"msg\":\"自动创建数据库成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/jwt/jsonInBlacklist": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jwt"
                ],
                "summary": "jwt加入黑名单",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"拉黑成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/niepan/questions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Niepan"
                ],
                "summary": "根据知识点获取题目 - 用于涅槃",
                "parameters": [
                    {
                        "type": "string",
                        "description": "对应涅槃知识点，使用 , 分割。示例：JavaScript,js简介,简介,JS有什么作用",
                        "name": "point",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "所在页面 默认值：1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分页大小 默认值：1",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.GetQuestions2NiepanResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.GetQuestions2NiepanResponse"
                        }
                    }
                }
            }
        },
        "/oauth/ourspark": {
            "get": {
                "tags": [
                    "OAuth"
                ],
                "summary": "OAuth 登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ]
            }
        },
        "/questions/answer/:id": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "查询问题答题情况",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户答题id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.QuestionResultResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.QuestionResultResponse"
                        }
                    }
                }
            }
        },
        "/questions/question/:id": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "查询某个问题",
                "parameters": [
                    {
                        "type": "string",
                        "description": "问题id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.AddQuestionResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.AddQuestionResponse"
                        }
                    }
                }
            }
        },
        "/questions/random": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "根据章节随机推荐题目",
                "parameters": [
                    {
                        "description": "章节id列表",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetQuestionByChaptersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.RandomQuestionResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.RandomQuestionResponse"
                        }
                    }
                }
            }
        },
        "/questions/submit": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "提交某个问题答案",
                "parameters": [
                    {
                        "description": "答案",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Answer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/tags": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tag"
                ],
                "summary": "获取所有标签",
                "responses": {
                    "200": {
                        "description": "response.Response{data: GetTagsResponse}",
                        "schema": {
                            "$ref": "#/definitions/v1.GetTagsResponse"
                        }
                    }
                }
            }
        },
        "/test/just4test": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Home"
                ],
                "summary": "HelloWorld",
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": {}, \"msg\": \"just4test\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "获取用户信息",
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.SysUserResponse}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/DeleteQuestionFromWrongQuestionBook": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "删除错题",
                "parameters": [
                    {
                        "type": "string",
                        "description": "问题id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response.Response{data: response.DelQuestionFromQuestionBook}",
                        "schema": {
                            "$ref": "#/definitions/response.DelQuestionFromQuestionBook"
                        }
                    }
                }
            }
        },
        "/user/WrongQuestion": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "查询用户错题历史",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在页面 默认值：1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分页大小 默认值：10",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "model.Response{data: response.GetQuestionHistoryResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.GetQuestionHistoryResponse"
                        }
                    }
                }
            }
        },
        "/user/changePassword": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "用户修改密码",
                "parameters": [
                    {
                        "description": "用户名, 原密码, 新密码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ChangePasswordStruct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"修改成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/exams": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "查询用户考试历史",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在页面 默认值：1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分页大小 默认值：10",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "model.Response{data: response.GetExamHistoryResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.GetExamHistoryResponse"
                        }
                    }
                }
            }
        },
        "/user/questions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "查询用户做题历史",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所在页面 默认值：1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分页大小 默认值：10",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "model.Response{data: response.GetQuestionHistoryResponse}",
                        "schema": {
                            "$ref": "#/definitions/response.GetQuestionHistoryResponse"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "用户注册账号",
                "parameters": [
                    {
                        "description": "用户名, 昵称, 密码, 角色ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SysUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"注册成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/setUserInfo": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "设置用户信息",
                "parameters": [
                    {
                        "description": "ID, 用户名, 昵称, 头像链接",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SysUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"设置成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/xapi/new": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "xAPI"
                ],
                "summary": "学习行为数据",
                "parameters": [
                    {
                        "description": "学习行为数据",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.XAPIData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": {}, \"msg\": \"success\"}",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Chapters": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.ExaFileUploadAndDownload": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "model.ExamHistory": {
            "type": "object",
            "properties": {
                "endTime": {
                    "type": "string"
                },
                "examId": {
                    "type": "integer"
                },
                "examTitle": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                }
            }
        },
        "model.Exams": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Questions"
                    }
                },
                "title": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "model.QuestionHistory": {
            "type": "object",
            "properties": {
                "endTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "questionId": {
                    "type": "integer"
                },
                "questionResult": {
                    "$ref": "#/definitions/model.QuestionResult"
                },
                "startTime": {
                    "type": "string"
                }
            }
        },
        "model.QuestionOptionResult": {
            "type": "object",
            "properties": {
                "isChoosed": {
                    "type": "boolean"
                },
                "isRight": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.QuestionOptions": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isRight": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.QuestionResult": {
            "type": "object",
            "properties": {
                "analysis": {
                    "type": "string"
                },
                "isRight": {
                    "type": "boolean"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.QuestionOptionResult"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "model.Questions": {
            "type": "object",
            "properties": {
                "analysis": {
                    "type": "string"
                },
                "chapterId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.QuestionOptions"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Tags"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "model.SysAuthority": {
            "type": "object",
            "properties": {
                "authorityId": {
                    "type": "integer"
                },
                "authorityName": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "defaultRouter": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.SysUser": {
            "type": "object",
            "properties": {
                "authority": {
                    "$ref": "#/definitions/model.SysAuthority"
                },
                "authorityId": {
                    "type": "integer"
                },
                "headerImg": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickName": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.Tags": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "layer1": {
                    "type": "string"
                },
                "layer2": {
                    "type": "string"
                },
                "layer3": {
                    "type": "string"
                },
                "layer4": {
                    "type": "string"
                }
            }
        },
        "model.XAPIData": {
            "type": "object",
            "properties": {
                "actor": {
                    "$ref": "#/definitions/model.XActor"
                },
                "authority": {
                    "type": "object"
                },
                "context": {
                    "$ref": "#/definitions/model.XContext"
                },
                "object": {
                    "type": "integer"
                },
                "result": {
                    "type": "object"
                },
                "timestamp": {
                    "type": "string"
                },
                "verb": {
                    "type": "integer"
                }
            }
        },
        "model.XActor": {
            "type": "object",
            "properties": {
                "uuid": {
                    "type": "string"
                }
            }
        },
        "model.XContext": {
            "type": "object",
            "properties": {
                "device": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                }
            }
        },
        "request.AddQuestionOption": {
            "type": "object",
            "properties": {
                "isRight": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "request.AddQuestionRequest": {
            "type": "object",
            "properties": {
                "analysis": {
                    "type": "string"
                },
                "chapterId": {
                    "type": "integer"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.AddQuestionOption"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "request.Answer": {
            "type": "object",
            "properties": {
                "endTime": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "questionId": {
                    "type": "integer"
                },
                "startTime": {
                    "type": "string"
                }
            }
        },
        "request.CasbinInReceive": {
            "type": "object",
            "properties": {
                "authorityId": {
                    "type": "string"
                },
                "casbinInfos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.CasbinInfo"
                    }
                }
            }
        },
        "request.CasbinInfo": {
            "type": "object",
            "properties": {
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "request.ChangePasswordStruct": {
            "type": "object",
            "properties": {
                "newPassword": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.EditQuestionOption": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isRight": {
                    "type": "boolean"
                },
                "questionId": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "request.EditQuestionRequest": {
            "type": "object",
            "properties": {
                "analysis": {
                    "type": "string"
                },
                "chapterId": {
                    "type": "integer"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.EditQuestionOption"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "request.Exam": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.Question"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "request.ExamAnswer": {
            "type": "object",
            "properties": {
                "endTime": {
                    "type": "string"
                },
                "examId": {
                    "type": "integer"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.ExamAnswerQuestion"
                    }
                },
                "startTime": {
                    "type": "string"
                }
            }
        },
        "request.ExamAnswerQuestion": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "request.ExamReq": {
            "type": "object",
            "properties": {
                "questionIDs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "request.GetQuestionByChaptersRequest": {
            "type": "object",
            "properties": {
                "chapterIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "request.InitDB": {
            "type": "object",
            "required": [
                "dbName",
                "userName"
            ],
            "properties": {
                "dbName": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "request.Login": {
            "type": "object",
            "properties": {
                "captcha": {
                    "type": "string"
                },
                "captchaId": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.PageInfo": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                }
            }
        },
        "request.Question": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.QuestionOption"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "request.QuestionOption": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "response.AddQuestionResponse": {
            "type": "object",
            "properties": {
                "question": {
                    "$ref": "#/definitions/model.Questions"
                }
            }
        },
        "response.DelQuestionFromQuestionBook": {
            "type": "object",
            "properties": {
                "question": {
                    "type": "object"
                }
            }
        },
        "response.DelQuestionResponse": {
            "type": "object",
            "properties": {
                "question": {
                    "type": "object"
                }
            }
        },
        "response.ExamResponse": {
            "type": "object",
            "properties": {
                "exam": {
                    "$ref": "#/definitions/request.Exam"
                }
            }
        },
        "response.ExamResult": {
            "type": "object",
            "properties": {
                "endTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.QuestionResult"
                    }
                },
                "score": {
                    "type": "integer"
                },
                "startTime": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "totalScore": {
                    "type": "integer"
                }
            }
        },
        "response.ExamResultResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "$ref": "#/definitions/response.ExamResult"
                }
            }
        },
        "response.GetExamHistoryResponse": {
            "type": "object",
            "properties": {
                "examHistory": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ExamHistory"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.GetExamsResponse": {
            "type": "object",
            "properties": {
                "exams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Exams"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.GetQuestionHistoryResponse": {
            "type": "object",
            "properties": {
                "questionHistory": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.QuestionHistory"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.GetQuestions2NiepanResponse": {
            "type": "object",
            "properties": {
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Questions"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.GetQuestionsResponse": {
            "type": "object",
            "properties": {
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Questions"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.QuestionResultResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "$ref": "#/definitions/model.QuestionResult"
                }
            }
        },
        "response.RandomQuestionResponse": {
            "type": "object",
            "properties": {
                "question": {
                    "$ref": "#/definitions/model.Questions"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.SubmitExamResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "v1.GetChaptersResponse": {
            "type": "object",
            "properties": {
                "chapters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Chapters"
                    }
                }
            }
        },
        "v1.GetTagsResponse": {
            "type": "object",
            "properties": {
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Tags"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "x-token",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "online-exam API",
	Description: "online exam APIs",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
